<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="0" hostname="Sarah" failures="4" tests="14" name="Surefire test" time="42.06" errors="0" timestamp="2025-07-16T13:09:22 IST">
  <testcase classname="api.test.DDTests" name="testPostUser" time="3.067"/>
  <testcase classname="api.test.DDTests" name="testPostUser" time="1.124"/>
  <testcase classname="api.test.DDTests" name="testPostUser" time="1.165"/>
  <testcase classname="api.test.DDTests" name="testPostUser" time="1.163"/>
  <testcase classname="api.test.DDTests" name="testPostUser" time="1.153"/>
  <testcase classname="api.test.DDTests" name="testDeleteUser" time="3.214">
    <failure type="java.lang.AssertionError" message="expected [200] but found [404]">
      <![CDATA[java.lang.AssertionError: expected [200] but found [404]
at api.test.DDTests.testDeleteUser(DDTests.java:44)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
... Removed 38 stack frames]]>
    </failure>
  </testcase> <!-- testDeleteUser -->
  <testcase classname="api.test.DDTests" name="testDeleteUser" time="3.166">
    <failure type="java.lang.AssertionError" message="expected [200] but found [404]">
      <![CDATA[java.lang.AssertionError: expected [200] but found [404]
at api.test.DDTests.testDeleteUser(DDTests.java:44)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
... Removed 38 stack frames]]>
    </failure>
  </testcase> <!-- testDeleteUser -->
  <testcase classname="api.test.DDTests" name="testDeleteUser" time="3.301"/>
  <testcase classname="api.test.DDTests" name="testDeleteUser" time="3.139">
    <failure type="java.lang.AssertionError" message="expected [200] but found [404]">
      <![CDATA[java.lang.AssertionError: expected [200] but found [404]
at api.test.DDTests.testDeleteUser(DDTests.java:44)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
... Removed 38 stack frames]]>
    </failure>
  </testcase> <!-- testDeleteUser -->
  <testcase classname="api.test.DDTests" name="testDeleteUser" time="3.237">
    <failure type="java.lang.AssertionError" message="expected [200] but found [404]">
      <![CDATA[java.lang.AssertionError: expected [200] but found [404]
at api.test.DDTests.testDeleteUser(DDTests.java:44)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
... Removed 38 stack frames]]>
    </failure>
  </testcase> <!-- testDeleteUser -->
  <testcase classname="api.test.UserTests" name="testPostUser" time="1.103"/>
  <testcase classname="api.test.UserTests" name="testGetUser" time="6.233"/>
  <testcase classname="api.test.UserTests" name="testUpdateUser" time="7.347"/>
  <testcase classname="api.test.UserTests" name="testDeleteUser" time="1.141"/>
</testsuite> <!-- Surefire test -->
